/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
SmartCANJaguar* RobotMap::driveTrainrightFront = NULL;
SmartCANJaguar* RobotMap::driveTrainrightBack = NULL;
SmartCANJaguar* RobotMap::driveTrainleftFront = NULL;
SmartCANJaguar* RobotMap::driveTrainleftBack = NULL;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();
	driveTrainrightFront = new SmartCANJaguar(2);
	
	
	driveTrainrightBack = new SmartCANJaguar(3);
	
	
	driveTrainleftFront = new SmartCANJaguar(4);
	
	
	driveTrainleftBack = new SmartCANJaguar(5);
	
	
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
